### ISSUE TITLE
add a license!

### ISSUE THREAD

**Issue by dayne** [FineTralfazz/NookBot#14]
The NookBot in UAF-CS discord is great. I was hoping to inspire some Upward Bound students to hack together a bot for another discord server by pointing them towards NookBot to get started.  However I noticed there isn't a license file to let me know if/how they could safely engage with this source code.

While there are still only 4 contributors I'd suggest getting this question resolved.

Thanks

**Comment by FineTralfazz** [comment]
Done, thanks for bringing this to our attention.
